### ISSUE TITLE
Mistake in requirements.txt/pyproject.toml

### ISSUE THREAD

**Issue by vitasha10** [SocAIty/face2face#5]
![image_2024-07-15_16-39-39](https://github.com/user-attachments/assets/565fc4e0-8441-43d0-9baf-f9caea1aaca4)

Please give instruction how to setup this project. It's imposible, in any case I have a dependency mistake..
Also please define Python version. E.g. Onnxryntime 1.9.0 requires Python 3.6-3.9

If you can please share Dockerfile example with simple python script without gpu.

Thank you very much!

**Comment by w4hns1nn** [comment]
Hi vitasha, thank you for raising the issues:
- I currently work with the Media-Toolkit version > 0.0.6 and
- Python 3.10.11. 
At least with that combination it works fine.

Definitely would help to set it up in an test environment with older python version.

For ONNX runtime. It's stuck to that old version, because the roop version of insightface is a little bit old.
Probably it is possible to update the ONNX version and convert the models in a way that they are compatible with the new version. 

I've created a branch for compatibility issu related tasks.
Do you think you could look into something?

I think Docker support would fit into another issue ;) - especially if it should work together with FastTaskAPI.

Kind regards
